### ISSUE TITLE
Hilfe für dummies

### ISSUE THREAD

**Issue by chatelao** [geofabrik/docker-apache-tirex#1]
Kann mir jemand das einfachste am Ganzen sagen:
- Unter welcher URL finde ich die Kacheln genau? Suche seit 1.5h ... erfolglos (peinlichst)

**Comment by knowname** [comment]
Wenn der Docker-Container z. B. die Adresse 172.21.0.3 hat, dann sollte der Apache eine Slippymap unter 172.21.0.3/osm/slippymap.html bereitstellen.
Die Adresse der Tiles ist dann z. B. 172.21.0.3/tiles/osmbright/0/0/0.png ( Z/X/Y.png ).
